version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
  - "3000:3000"
environment:
  MB_DB_FILE: /metabase-data/metabase.db
volumes:
  - ./metabase-data:/metabase-data
  - ./plugins:/plugins
restart: always
